use-grammars.only = ["ink"]

[[language]]
name = "ink"
scope = "source.ink"
file-types = ["ink"]
comment-tokens = "//"
block-comment-tokens.start = "/*"
block-comment-tokens.end = "*/"
indent.unit = " "
indent.tab-width = 2
soft-wrap.enable = true


[[grammar]]
name = "ink"
source = { git = "git@github.com:wldmr/tree-sitter-ink.git", rev = "latest"}
